### ISSUE TITLE
Urls don't resolve in spec file

### ISSUE THREAD

**Issue by dsentinel** [iris-edu/ispaq#1]
Several urls fail when creating the conda env.

Like so:
`CondaError: CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/r/osx-64/ncurses-5.9-8.tar.bz2>`

Attached spec works. I tried to push a branch, but did not have permissions.
[ispaq-spec2.txt](https://github.com/iris-edu/ispaq/files/784201/ispaq-spec2.txt)

**Comment by rcasey-iris** [comment]
Thank you for the notice on this.  We are still in beta with this project, but recognize that the conda spec file is very OS specific and will require a more OS-agnostic solution before release.  The documentation is getting updated to clarify in areas that need attention.

**Comment by gillian-iris** [comment]
We now have an installation that is not dependent on specific urls in a spec file.
