### ISSUE TITLE
install failing in line 160 of ispaq.py 

### ISSUE THREAD

**Issue by sjohn19-git** [iris-edu/ispaq#16]
when I am installing ISPAQ, I am getting an error due to applying the `.tolist()` on `rpy2.robjects.vectors.StrVector` object. This is breaking the code every time I run ./run_ispaq.py. 

Traceback (most recent call last):
  File "./run_ispaq.py", line 15, in <module>
    main()
  File "/home/sjohn/AON_PROJECT/ispaq/ispaq/ispaq.py", line 160, in main
    installed_names = ro.conversion.rpy2py(r_installed.rownames).tolist()      
AttributeError: 'StrVector' object has no attribute 'tolist'

could you please tell me how to resolve this?

Thank you

**Comment by gillian-iris** [comment]
Apologies for the late reply, are you still having trouble with this? If so, were there any errors when installing the conda packages? And what is the result of the following command when you are in your ispaq conda environment:
`conda list`

**Comment by sjohn19-git** [comment]
Thank you for replying. I was able to solve this issue by renaming some Python libraries.

`moving the directory ~/.local/lib to ~/.local/lib_bak`
